# Default configuration values
DEFAULT_LEVEL: str = "INFO"
DEFAULT_LOG_FORMAT: str = "DEFAULT"
DEFAULT_DATE_FORMAT: str = "DEFAULT"
DEFAULT_RICH_TRACEBACKS: bool = True
DEFAULT_TRACEBACK_SUPPRESS: list[str] = []
